apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-phpserver
  labels:
    app: phpserver
spec:
  selector:
    matchLabels:
      app: phpserver
  replicas: 3
  template:
    metadata:
      labels:
        app: phpserver
    spec:
      containers:
      - name: container-phpserver
        image: "evandroig/php-server:v14"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
          successThreshold: 1
        envFrom:
        - secretRef:
            name: php-server-secret
        env:
        - name: name
          value: Evandro Dunga
        volumeMounts:
        - name: config
          mountPath: "/var/www/html/file/"
      volumes:
      - name: config
        configMap:
          name: configmap-family
          items:
          - key: members
            path: myfamily.txt
