apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-phpserver
  labels:
    app: phpserver
spec:
  selector:
    matchLabels:
      app: phpserver
  replicas: 3
  template:
    metadata:
      labels:
        app: phpserver
    spec:
      containers:
      - name: container-phpserver
        image: "evandroig/php-server:v5"
        env:
        - name: name
          value: Evandro Dunga
