apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-phpserver
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30
