apiVersion: v1
kind: Service
metadata:
  name: service-loadbalance-phpserver
spec:
  selector:
    app: phpserver
  type: LoadBalancer
  ports:
  - name: phpserver-service
    port: 80
    targetPort: 80
    protocol: TCP
